version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/Ikechukwu980/aws-serverless-project.git
      - ls -l
      - cd aws-serverless-project
      - echo "Installing dependencies..."
      - npm install
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - echo "Setting AWS CLI region to us-east-1..."
      - aws configure set region us-east-1
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
      - ls -l

  pre_build:
    commands:
      - echo "Reinitializing Terraform..."
      - cd terraform-modules
      - ls -l
      - terraform init -reconfigure  # Reinitialize Terraform with the new configuration
      - rm -rf .terraform  # Clear the .terraform directory
      - terraform init  # Reinitialize after clearing cache
      - echo "Running Terraform plan..."
      - terraform plan
      - ls -l

  build:
    commands:
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform provisioning completed!"

artifacts:
  files:
    - '**/*'
