version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      terraform: 1.5
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/webmagicinformatica/serverless-cf-api-project.git
      - cd serverless-cf-api-project
      - echo "Installing dependencies..."
      - npm install
      - npm install -g aws-cli
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve
      # - echo "Building the Lambda functions..."
      # - cd src/handlers
      # - npm install
      # - echo "Zipping Lambda functions..."
      # - zip -r ../../put-contact-form.zip put-item.mjs node_modules
      # - zip -r ../../get-contact-form.zip get-by-id.mjs node_modules
      # - zip -r ../../get-all-contacts.zip get-all-items.mjs node_modules
      # - cd ../..

  post_build:
    commands:
      # - echo "Deploying Lambda functions..."
      # - aws lambda update-function-code --function-name PutContactForm --zip-file fileb://put-contact-form.zip
      # - aws lambda update-function-code --function-name GetContactFormById --zip-file fileb://get-contact-form.zip
      # - aws lambda update-function-code --function-name GetAllContactForms --zip-file fileb://get-all-contacts.zip
      # - echo "Copying index.html to S3..."
      # - aws s3 cp ./UI/index.html s3://my-static-website/ --acl public-read
      - echo "Terraform provisioning completed!"

artifacts:
  files:
    - '**/*'
